### ISSUE TITLE
Compilation error: driver/spi_slave.h

### ISSUE THREAD

**Issue by lezlikov** [hideakitai/ESP32SPISlave#13]
Compilation error: driver/spi_slave.h: No such file or directory
Help pls!

**Comment by lezlikov** [comment]
![image](https://user-images.githubusercontent.com/73757896/203981999-33df1664-d39b-40a0-bd43-d4de8fce38c9.png)

**Comment by AndyW999** [comment]
I also get this -

Compilation error: driver/spi_slave.h: No such file or directory

Using Arduino 2.0.4

And if I try and use PlatformIO as soon as it goes into the Loop - 

E (154) spi_slave: spi_slave_queue_trans(291): data transfer > host maximum

Any ideas anybody?

Thanks

Andy.

**Comment by hideakitai** [comment]
This library does not support the latest ESP32 core now. Please let me know:

- ESP32 Board (esp32, s3, c3, etc): 
- ESP32 Board Firmware Version (see board manager):
- Library Version of ESP32SPISlave:

**Comment by hideakitai** [comment]
Fixed by https://github.com/hideakitai/ESP32SPISlave/pull/21
