### ISSUE TITLE
ESP32SPISlave.h

### ISSUE THREAD

**Issue by Mike083** [hideakitai/ESP32SPISlave#14]
Compiling the slave_echo.ino example gives this error message:

In file included from C:\Users\MW\Documents\Arduino\libraries\ESP32SPISlave\examples\slave_echo\slave_echo.ino:1:
c:\Users\MW\Documents\Arduino\libraries\ESP32SPISlave/ESP32SPISlave.h:22:37: error: 'HSPI_HOST' was not declared in this scope
             spi_host_device_t host {HSPI_HOST};
                                     ^~~~~~~~~ 
Could this be related to my trying to compile this for a ESP32S3 board and not the original ESP32?  Has this library been used with a ESP32-S3-WROOM-1 module?

(Arduino IDE v2.0.2)
Thanks

**Comment by hideakitai** [comment]
Fixed by https://github.com/hideakitai/ESP32SPISlave/pull/21
