### ISSUE TITLE
Transfer Size

### ISSUE THREAD

**Issue by AndyW999** [hideakitai/ESP32SPISlave#15]
In ESP32SPISlave.h the maximum transfer size is set to SOC_SPI_MAXIMUM_BUFFER_SIZE which is 64.

I wish to transfer up to 640 bytes.

I am using the VSPI SPI in master mode with the usual SPI.h library and this works fine with 640 byte transfers.

So is there a way around this or do I need to use your DMA library - please tell me it will do transfers this size?

Thanks

Andy.

**Comment by hideakitai** [comment]
You can use my other library [ESP32DMASPI](https://github.com/hideakitai/ESP32DMASPI) to send/receive more than 64 bytes. Please try it.

**Comment by AndyW999** [comment]
I used it and it works great!

Thanks

Andy.
