### ISSUE TITLE
Support for ESP32-S3.

### ISSUE THREAD

**Issue by magicsmoke** [hideakitai/ESP32SPISlave#20]
Thanks for the library so far.

I'm having issues with support for the ESP32-S3 processor.

Will support for the latest version of the IDF and this processor be added?

**Comment by hideakitai** [comment]
Yes, I will soon.

**Comment by hideakitai** [comment]
Fixed by https://github.com/hideakitai/ESP32SPISlave/pull/21

**Comment by magicsmoke** [comment]
Thanks a lot!!
