### ISSUE TITLE
No data to Master problem

### ISSUE THREAD

**Issue by danm19** [hideakitai/ESP32SPISlave#3]
Hi, @hideakitai! 

I'm having a problem when I use: 
Ex: slave.wait(spi_slave_rx_buf, BUFFER_SIZE); // no data to master

In this case, the slave device receives an aleatory data.

**Comment by danm19** [comment]
Hi, @hideakitai!
I'm using "slave_simple_wait.ino" from examples directory. I'm using also TIVA TM4C1294 as master. 

If I use: slave.wait(spi_slave_rx_buf, spi_slave_tx_buf, BUFFER_SIZE);
I receive all the data in my ESP32 module correctly, but when I remove the parameter spi_slave_tx_buf, I always receive the same random data, and it doesn't matter if I'm using VSPI or HSPI. 

Example when I use slave.wait(spi_slave_rx_buf, BUFFER_SIZE);
Sending "Corinthians" from TIVA to ESP32
Receiving "z z z z z z z z z z z" in ESP32

**Comment by hideakitai** [comment]
Hmm, that's strange behavior. I can't test it now, but can you let me know

- the ide you use (Arduino IDE or PlatformIO?)
- the version of arduino-esp32 firmware
- if it fixes when you disconnect the hardware connection of MISO

**Comment by hideakitai** [comment]
I will close this issue but feel free to reopen if you still have a problem.
