### ISSUE TITLE
What spi_bus value to use in slave.begin() for ESP32-S3 based modules?

### ISSUE THREAD

**Issue by karunt** [hideakitai/ESP32SPISlave#45]
When using an ESP32-S3 based module for my device, what value for spi_bus should I use in slave.begin()? Should it be "FSPI" if using SPI2 and "HSPI" if using SPI3? Just want to make sure I'm reading your readme file correctly. Thanks.

**Comment by hideakitai** [comment]
Hi @karunt 

As mentioned in the README, the default SPI is HSPI, and the pins are (MOSI, MISO, SCK. SS) = (11, 13. 12. 10). However, you can change them independently and flexibly. Using the default one is good if you don't need to change them.

**Comment by hideakitai** [comment]
If you still need help, please reopen this issue.
