### ISSUE TITLE
Dataloss

### ISSUE THREAD

**Issue by mrsaad381** [hideakitai/ESP32SPISlave#46]
Hi  i am collecting data from Master  launchxl f28379d which set SPIMODE 0 SCLK 5MHz and  when my data sampling is set to 10khz it working fine but if i increase it speed to 20khz so esp32 is missing 3 samples everytime for example my data is come like this 0 1 2 3 4 5 6 7 8 
esp32 read 0 3 6 9 so it decimate by factor of 3 and i troubleshoot my code it spend to much time on  
These lines.
 slave.queue(NULL, rx_buf, BUFFER_SIZE);
      slave.trigger();
      
    Below is my   
void spiDataCaptureTask(void *parameter) {
  while (1) {
    // Queue and handle transactions
    if (slave.hasTransactionsCompletedAndAllResultsHandled()) {
      slave.queue(NULL, rx_buf, BUFFER_SIZE);
      slave.trigger();
    }

    // Process received transactions
    if (slave.hasTransactionsCompletedAndAllResultsReady(1)) {
      size_t received_bytes = slave.numBytesReceived();
      callCount++;
      for (size_t i = 0; i < received_bytes; i++) {
        // Send data to ring buffer
        if (xRingbufferSend(bufferHandle, &(rx_buf[i]), sizeof(rx_buf[i]), pdMS_TO_TICKS(0)) != pdTRUE) {
          Serial.println("Failed to send message to ring buffer!");
          return;
        }
      }
      lastReceiveTime = millis(); // Reset the timer on successful data reception
    }
  }
}

**Comment by hideakitai** [comment]
@mrsaad381 Sorry for not getting back to you sooner. If you use the [example code](https://github.com/hideakitai/ESP32SPISlave/blob/main/examples/transfer_one_by_one/transfer_one_by_one_slave/transfer_one_by_one_slave.ino) as is, do you know if it works correctly at 20khz? The example works fine up to at least 8MHz. If the example also does not work correctly, your hardware may have a problem. See here.
