### ISSUE TITLE
simple way to do LSB transmissions ?

### ISSUE THREAD

**Issue by L10N37** [hideakitai/ESP32SPISlave#5]
I am using your library for a project but it's a console that sends LSB first.

Is there a simple way to change this as I'm having to convert everything at the moment, just making baby steps but this is a big issue for a beginner :P

**Comment by hideakitai** [comment]
Sorry for the late reply. Selecting MSB/LSB is the scope of master device. And most of the devices use MSB first by default, so I don't have a plan to do it. Please refer https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_master.html#transactions-with-integers-other-than-uint8-t

**Comment by L10N37** [comment]
someone helped me fix this a few weeks back. line30 of slave CPP. 

if_cfg.flags= SPI_SLAVE_BIT_LSBFIRST; 

it seems to have worked as I've captured a lot of successful transmissions.
